### ISSUE TITLE
영업시스템이란?

### ISSUE THREAD

**Issue by jsmin6330** [Team5-be01-Final-Project/.github#10]
영업관리시스템이란 무엇인가에 대해서 주관적인 생각이 들어갔지만, 
간단하게 정리해봤습니다.

영업시스템이란 무엇인가? 
효율적인 영업을 하기 위해 참고하는 시스템
영업을 잘 해서 높은 매출과, 높은 수익을 잘 내는 것이 목표.
효율적인 영업 = 매출액 ↑, 이익 ↑, 원가 ↓

그렇다면 영업시스템에 기본적으로 필요한 것은?
매출을 보는 화면 -> 매출을 등록 하는 행위에 대한 기능 필요
이익을 계산하기 위해서는? 상품의 원가와 매출액이 필요.
제일 단순하게 (이익 = 매출 - 원가)
그럼 원가는 어디서 가져오는가? -> 상품 -> 상품 관리가 필요

그래서 제일 기본적으로 필요한 기능
1) 매출을 보는 화면(집계)
2) 매출을 등록하는 기능
3) 상품 관리하는 기능

도메인에 따라 추가될 수 있는 부가적인 기능
+ 유저관리
+ 재고관리(단일상품,  제조상품)
+ 거래처관리(상품매입처, 매출거래처)
+ 영업지점 관리
. . . . . ETC

**Comment by INAUGURATE-Ryong** [comment]
![LGTM](https://i.lgtm.fun/2pvm.gif)
