### ISSUE TITLE
2차 멘토링 준비

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [Team5-be01-Final-Project/.github#18]
- [ ] 2차 기획안 작성
https://docs.google.com/document/d/1FBpvcKzNSAYea77dusQbU8n_9-JMTb-4CosF-qLE_xM/edit
- [ ] 요구사항 정의서 작성
https://web.thinkwise.co.kr/guest/map/25da594c-1846-4040-84e3-6da9f17bcaae

**Comment by dhkdtld37** [comment]
2024-03-08 PM 07:10 시작

1. 콜드체인 관련 도메인을 사용하려면 실시간으로 조회, 모니터링 할 수 있는 느낌으로 사용. 자동으로 데이터와 연동 및 새로고침 (온도 이탈에 따른 푸쉬 알림(팝업, 메일 MMS)으로 구현) > crontab
2. 알림 관련해서 매출이나 다른 항목도 추가 포함
3. 대시보드 데이터를 실시간으로 커스텀 할 수 있는 기능 > 그러기 위해서는 선택할 수 있는 뷰의 개수 추가가 필요
4. 대시보드 매출에 있어서 총합계, 월별, 주별, 일별 좀 더 디테일한 데이터와 지표가 필요
5. 리스트 조회 후 등록 및 수정 같은 경우 새 페이지와 팝업의 결정이 필요
6. 알림 메일에 따른 전송 로그 선택 리스트도 필요, 알림 현황 조회, 대상자 지정
7. 삭제 기능의 경우 db와 별개로 프론트에서만 숨김 처리
8. 출고와 매출의 경우 출고의 경우만 db와 연동해서 매출과는 별개로?
9. 재고의 경우 리스트 현황 화면에 등록 화면과 합본(등록은 팝업, 행 추가?), 재고 리스트에 상품에 대한 세부 항목도 추가 > 관련 화면도 합치기?
10. 인센티브 관련 항목 별개의 화면과 db가 필요하기 때문에 기능은 수정만, 인센티브는 없어도 무관하니 차라리 상품 테이블에 인센티브 가중치로 추가
10-1. 인센티브는 별도의 계산 없이 개인 및 팀 순위별 가중치 추가
11. 콜드체인으로서 강조를 하려면 배송에 대한 기능 혹은 페이지가 필요 > 다만 영업이라는 주제와는 멀어질 수도 있으니 유의
12. 콜드체인이라는 아이템으로 영업으로 어필을 하려면 배송, 안정성 달성률에 대한 성공적인 수치로 보여준 뒤 이로 홍보함으로써 영업에 대한 주문 인상률, 영업에 긍정적인 영향을 설명
