### ISSUE TITLE
BPS Logo 정하기

### ISSUE THREAD

**Issue by parc02** [Team5-be01-Final-Project/.github#27]
각자 원하는 로고 하나씩 comment 달아주시면 감사하겠습니다.

**Comment by parc02** [comment]
![image](https://github.com/Team5-be01-Final-Project/.github/assets/148880521/37ebe925-2929-425f-8398-6a4e811b541a)

**Comment by INAUGURATE-Ryong** [comment]
![image](https://github.com/Team5-be01-Final-Project/.github/assets/62015109/0b6d9ac0-a3e5-466f-ba3f-92f27f48f024)

**Comment by dhkdtld37** [comment]
![image](https://github.com/Team5-be01-Final-Project/.github/assets/149128094/8880520b-43bd-427e-bdf7-966165329106)

**Comment by jsmin6330** [comment]
![BPS로고](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/0425b3e3-d842-47f5-a8e6-a5cc0299e6ff)

**Comment by jsmin6330** [comment]
글자 로고 PNG 파일
![BPS로고글자버전](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/2e39c7bf-4a63-464d-854c-633ee74fe863)

**Comment by jsmin6330** [comment]
로고 PNG 파일 수정 버전
![BPS로고v2](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/58307403-dab1-4d51-ad0f-f7af385733fc)

**Comment by jsmin6330** [comment]
![BPS로고_70](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/089bd1b7-d56c-473f-9e63-3efdb66c78f7)
![BPS로고_173](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/7ef4f093-e965-4f5d-9cfb-17e4992c692f)
