### ISSUE TITLE
3차 멘토링 준비

### ISSUE THREAD

**Issue by dhkdtld37** [Team5-be01-Final-Project/.github#31]
### 2024-03-12 3차 멘토링

- [x] WBS 수정
- [x] 요구사항 명세서 검토
- [x] 화면 설계서 검토

**Comment by dhkdtld37** [comment]
2024-03-12 PM 06:55 

#### WBS

1. AWS 관련해서 일정 변경 고려할 것
2. 서버 구축에 대한 일정 고려할 것
3. 발표 시나리오는 사내 발표

#### 화면 설계서

1. 상품 관리
- 상품 리스트 : 검색 기능과 정렬 추가 ( 생물의약품 분류로 구분할지, atc 코드를 기준으로 할 지, 무엇을 위주로 검색할지 정할 것 )
- 피부과면 피부과, 호흡계면 호흡계 등 분류도 선택이 가능
- 기간에 따른 PK의 변경 고려 > WBS, 요구사항 명세서 또한 변경
- 상품의 리스트 조회보다는 거래처별, 단가별 등 다른 화면으로 변경을 고려

2. 전체적인 CRUD기능은 구현에 의의를 둘 것

3. 거래처 등록
- API 활용
- 계약 관련 항목(테이블) 추가 혹은 제외
- 화면 보충을 위해서 다른 항목 추가를 고려할 것 ( 계약 날짜, 병원 등급, 담당자 등 ... )
- 테이블의 경우 여러 항목으로 pk로 관리, pk값은 랜덤 생성으로 저장하기도 함

4. 인센티브 시뮬레이션 계산 및 조회
- 영업 사원이 총 판매 매출의 가중치와 그에 따른 매출액 혹은 목표치, 인센티브를 시뮬레이션하는 페이지
- 시뮬레이션 페이지는 판매 혹은 거래처, 매출현황과는 별개의 페이지 ( 마이 영업? )

5. 콜드체인 제거 고민 ??
- 영업 관리에 대한 추가적인 아이템과 페이지 추가에 따라 콜드체인 관련 화면 제거 고려

**Comment by parc02** [comment]
https://docs.google.com/document/d/10WP9lxOQqas4zN9S90L9qrXJhC8rYmTB/edit
