### ISSUE TITLE
[ 설정 ] 개발 환경 설정

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [Team5-be01-Final-Project/.github#37]
- [x] DB서버 구축
- [x] BE 개발 환경
  - [x] 깃허브 생성
  - [x] DB서버 연결
  - [x] yml파일 통일 
- [x] FE 개발 환경
- [x] PR 후 머지 전략 세우기
- [x] 깃 커밋 메세지 기준 세우기

**Comment by jsmin6330** [comment]
BE 개발 환경 설정: 

### 인텔리 J 리눅스 환경에 설치

1. 설치 파일 다운로드 
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/ef69b660-085a-4f2c-bc51-8a72adee6a98)

2. 다운 된 파일을 윈도우에서 리눅스 설치할 폴더로 이동(저는 APP 폴더 안에, 폴더 하나 만들어서 넣음)


3. 인텔리 J 설치 (우분투 환경에서)
```
$ pwd
/home/jsmin630/app/ideaIU-2023.3.5

$ ls
ideaIU-2023.3.5.tar.gz  ideaIU-2023.3.5.tar.gz:Zone.Identifier

$ tar xvfz ideaIU-2023.3.5.tar.gz
```

4. 
```
# bin 폴더로 이동
$ cd bin

$ ls
appletviewer.policy  fsnotifier       idea.sh           inspect.sh                    libdbm.so             repair
brokenPlugins.db     idea.png         idea.svg          jetbrains_client.sh           ltedit.sh             restarter
format.sh            idea.properties  idea64.vmoptions  jetbrains_client64.vmoptions  remote-dev-server.sh

# idea.sh 스크립트 실행(인텔리 J 실행)
$ ./idea.sh
```
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/72119bc7-81d7-4d2a-8850-a719f70f9ac1)

**Comment by jsmin6330** [comment]
BE 개발 환경 설정: 

### 인텔리 J 리눅스 환경에 설치 및 학생 인증, 실행

1. 설치 파일 다운로드 
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/ef69b660-085a-4f2c-bc51-8a72adee6a98)

2. 다운 된 파일을 윈도우에서 리눅스 설치할 폴더로 이동(저는 APP 폴더 안에, 폴더 하나 만들어서 넣음)


3. 인텔리 J 설치 (우분투 환경에서)
```
$ pwd
/home/jsmin630/app/ideaIU-2023.3.5

$ ls
ideaIU-2023.3.5.tar.gz  ideaIU-2023.3.5.tar.gz:Zone.Identifier

$ tar xvfz ideaIU-2023.3.5.tar.gz
```

4. 인텔리 J 실행
```
# bin 폴더로 이동
$ cd bin

$ ls
appletviewer.policy  fsnotifier       idea.sh           inspect.sh                    libdbm.so             repair
brokenPlugins.db     idea.png         idea.svg          jetbrains_client.sh           ltedit.sh             restarter
format.sh            idea.properties  idea64.vmoptions  jetbrains_client64.vmoptions  remote-dev-server.sh

# idea.sh 스크립트 실행(인텔리 J 실행)
$ ./idea.sh
```
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/61c6a0cb-f19c-4c83-bbd8-f52b4edbd0fb)
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/61852d41-1f94-49c5-85f1-57d70f5aba29)



5. 학생 라이센스 등록
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/4d4517d6-1f0d-4564-bb66-17ea8da7f338)
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/8dd8603d-c888-48ce-8da7-2b125247563f)
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/255c6124-e50f-4e9e-bd87-8ebfe38e7b38)
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/40089c17-b7c3-4406-92fe-0a8b58864e55)

윈도우에서 카피된 링크로 접속!!!
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/2afc598d-eae9-4c80-8603-59038555854e)
로그인 방식은 알아서 진행하세요

![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/fd1d4dd1-183c-468d-b775-d0e4dfcb97c6)

복사한 토큰을 빈 칸에 입력하세요.
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/baedbf12-7620-441f-836f-807c56bd6984)

![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/cb9646be-ea5d-4f75-923a-e61accc398ec)
마지막 캡쳐를 못떴는데, 이미지에 체크한 부분 클릭하고, 우측 하단에 continue 누르면 끝납니다.

**Comment by INAUGURATE-Ryong** [comment]
https://github.com/Team5-be01-Final-Project/Backend

세팅 완료~~ 
혹시 깃 이그노어 추가할거 있으면 적아놨다가 내일 한번에 업데이트 하시져~ 
application-private.yml 이거 이그노어에 추가해놨으니 
내일 application-private.yml 생생해서 DB정보값들과 오픈하면 안되는 것들은 저 파일에 넣고 진행하는방향으로 합시당~

**Comment by INAUGURATE-Ryong** [comment]
- https://youtrack.jetbrains.com/issue/IDEA-309713

window defender에서 wsl 파일을 지속적으로 읽어서 느려진다고 함.
그래서 
- Windows 보안"을 입력 후 들어가서
- "바이러스 및 위협 방지"를 클릭
- "바이러스 및 위협 방지 설정"에서 "설정 관리"를 클릭
- 필요한 경우 아래로 스크롤한 다음 '제외 추가 또는 제거'를 클릭

여기에 추가 눌러서 폴더를 wsl 폴더 랑 파일형식 눌러서 idea64.exe 입력

**Comment by jsmin6330** [comment]
### 마리아 DB 오라클 클라우드 개발용으로 구축

마리아 DB 오라클 클라우드에 개발용으로 구축해놨습니다.
aws 했을 때처럼 도커로 설치했어요.
application.properties에 DB 관련 설정 추가하고 포트 8081로 설정한 뒤에 
http://localhost:8081/ 로 접속해서 화면 뜨는 것까지 확인했습니다.
![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/26271e75-0e74-4a90-a492-1c52e6e2afc9)

![image](https://github.com/Team5-be01-Final-Project/.github/assets/150888333/115e1625-3231-4500-9256-174d6a1f34a7)

**Comment by INAUGURATE-Ryong** [comment]
@dhkdtld37 성현님 커밋메세지 어렵게 생각말구 쉽게쉽게! REF 몇개  드릴게여
- REF
  - https://velog.io/@msung99/Git-Commit-Message-Convension
  - https://overcome-the-limits.tistory.com/entry/%ED%98%91%EC%97%85-%ED%98%91%EC%97%85%EC%9D%84-%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8-git-%EC%BB%A4%EB%B0%8B%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
  - https://velog.io/@shin6403/Git-git-%EC%BB%A4%EB%B0%8B-%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

**Comment by dhkdtld37** [comment]
@INAUGURATE-Ryong 정말정말로 감사합니다 우용님 매우 큰 도움이 되었습니다

**Comment by jsmin6330** [comment]
yml파일 환경 변수 설정
- https://github.com/Team5-be01-Final-Project/Backend/issues/1#issue-2196403192
