### ISSUE TITLE
[ 설정 ] Organization 세팅

### ISSUE THREAD

**Issue by INAUGURATE-Ryong** [Team5-be01-Final-Project/.github#38]
- [x] 각자 기능 Milestone 제작 <- WBS 참조하면서 제작.
- [x] @dhkdtld37 차주 화요일 깃 브랜치 전략 최종 설명 
- [x] 이슈 태그 생성( BE / FE / TEST , 검토 등)  <- 논의 후 진행
- [ ] Wiki에 Docs 내용 옮기기  <- 추후 진행 예정
- [x] 슬랙 알람 ( 브랜치 생성 과 푸시도 넣을 지 말 지 고민)

**Comment by dhkdtld37** [comment]
### GM
- [ ] (2024-03-18) 깃 브랜치 전략 최종 설명 ( 수정중)
- [ ] WIKI ( 추가중 )
